### ISSUE TITLE
Android: no `com.wix.detox.config` package

### ISSUE THREAD

**Issue by Tommos0** [wix/Detox#2234]
**Describe the bug**
Hi, I'm having trouble setting up Detox with a brand new RN project (bootstrapped with `npx react-native init example`).

I've created a minimal example: https://github.com/Tommos0/detox-example . After setting up the new project and following the Detox docs, when I try to build:

```
$ ./gradlew assembleDebug assembleAndroidTest -DtestBuildType=debug

> Task :app:stripDebugDebugSymbols UP-TO-DATE
Compatible side by side NDK version was not found.

> Task :app:compileDebugAndroidTestJavaWithJavac FAILED
/p/example/android/app/src/androidTest/java/com/example/DetoxTest.java:5: error: package com.wix.detox.config does not exist
import com.wix.detox.config.DetoxConfig;
                           ^
/p/example/android/app/src/androidTest/java/com/example/DetoxTest.java:25: error: cannot find symbol
        DetoxConfig detoxConfig = new DetoxConfig();
        ^
  symbol:   class DetoxConfig
  location: class DetoxTest
/p/example/android/app/src/androidTest/java/com/example/DetoxTest.java:25: error: cannot find symbol
        DetoxConfig detoxConfig = new DetoxConfig();
                                      ^
  symbol:   class DetoxConfig
  location: class DetoxTest
3 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugAndroidTestJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 1s
36 actionable tasks: 2 executed, 34 up-to-date
```

**To Reproduce**

- [x] I have tested this issue on the latest Detox release and it still reproduces

Steps to reproduce:
1. `npx react-native init example`
2. `yarn add detox`
3. follow steps at https://github.com/wix/Detox/blob/master/docs/Introduction.Android.md
4. `./gradlew assembleDebug assembleAndroidTest -DtestBuildType=debug`

**Expected behavior**
It should build

**Environment (please complete the following information):**
 - Detox: 17.3.1
 - React Native: 0.63.2
 - Java: openjdk version "1.8.0_252"
 - OS:  Linux Manjaro

**Comment by a-eid** [comment]
I don't think that detox supports RN 0.63 as on now. #2196

**Comment by Tommos0** [comment]
I've tried with 0.62 and the same problem occurs.

Also, I just tried to build the example from https://github.com/wix/Detox/tree/master/examples/demo-react-native and I'm getting the same error

**Comment by Tommos0** [comment]
Recipe to reproduce:

```bash
docker run -it ubuntu:20.04

apt-get update
apt-get install -y git openjdk-8-jdk nodejs npm wget unzip

mkdir -p /opt/android-sdk/cmdline-tools
cd $_
wget https://dl.google.com/android/repository/commandlinetools-linux-6609375_latest.zip
unzip commandlinetools-linux-6609375_latest.zip
export ANDROID_HOME=/opt/android-sdk
export PATH=/opt/android-sdk/cmdline-tools/tools/bin:$PATH
yes | sdkmanager "build-tools;30.0.1"

cd /root
git clone https://github.com/wix/Detox.git --depth=1
cd Detox/examples/demo-react-native
npm install
npm install -g detox-cli

detox build --configuration android.emu.debug
```

Result:
```
> Task :app:compileDebugAndroidTestJavaWithJavac FAILED
/root/Detox/examples/demo-react-native/android/app/src/androidTest/java/com/example/DetoxTest.java:5: error: package com.wix.detox.config does not exist
import com.wix.detox.config.DetoxConfig;
                           ^
/root/Detox/examples/demo-react-native/android/app/src/androidTest/java/com/example/DetoxTest.java:25: error: cannot find symbol
        DetoxConfig detoxConfig = new DetoxConfig();
        ^
  symbol:   class DetoxConfig
  location: class DetoxTest
/root/Detox/examples/demo-react-native/android/app/src/androidTest/java/com/example/DetoxTest.java:25: error: cannot find symbol
        DetoxConfig detoxConfig = new DetoxConfig();
                                      ^
  symbol:   class DetoxConfig
  location: class DetoxTest
3 errors
```

**Comment by Tommos0** [comment]
FWIW, it there is no `config` here indeed:

```
als node_modules/detox/Detox-android/com/wix/detox/17.3.1/detox-17.3.1-sources.jar
Archive:  node_modules/detox/Detox-android/com/wix/detox/17.3.1/detox-17.3.1-sources.jar
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  2020-07-26 14:35   META-INF/
       25  2020-07-26 14:35   META-INF/MANIFEST.MF
        0  2020-07-26 14:32   com/
        0  2020-07-26 14:32   com/wix/
        0  2020-07-26 14:32   com/wix/invoke/
     2182  2020-07-26 14:32   com/wix/invoke/MethodUtilsExt.java
        0  2020-07-26 14:32   com/wix/invoke/parser/
      433  2020-07-26 14:32   com/wix/invoke/parser/JsonParser.java
        0  2020-07-26 14:32   com/wix/invoke/types/
      571  2020-07-26 14:32   com/wix/invoke/types/ObjectInstanceTarget.java
      581  2020-07-26 14:32   com/wix/invoke/types/InvocationTarget.java
      810  2020-07-26 14:32   com/wix/invoke/types/ClassTarget.java
     2361  2020-07-26 14:32   com/wix/invoke/types/Target.java
     5720  2020-07-26 14:32   com/wix/invoke/types/Invocation.java
        0  2020-07-26 14:32   com/wix/invoke/exceptions/
      273  2020-07-26 14:32   com/wix/invoke/exceptions/EmptyInvocationInstructionException.java
     1454  2020-07-26 14:32   com/wix/invoke/MethodInvocation.java
        0  2020-07-26 14:32   com/wix/detox/
      568  2020-07-26 14:32   com/wix/detox/NotificationDataParser.kt
     2706  2020-07-26 14:32   com/wix/detox/DetoxJUnitRunner.java
      743  2020-07-26 14:32   com/wix/detox/TestEngineFacade.kt
    10107  2020-07-26 14:32   com/wix/detox/Detox.java
        0  2020-07-26 14:32   com/wix/detox/instruments/
      274  2020-07-26 14:32   com/wix/detox/instruments/DetoxInstrumentsException.java
        0  2020-07-26 14:32   com/wix/detox/instruments/reflected/
     3855  2020-07-26 14:32   com/wix/detox/instruments/reflected/InstrumentsReflected.java
     3626  2020-07-26 14:32   com/wix/detox/instruments/reflected/InstrumentsRecordingReflected.java
      479  2020-07-26 14:32   com/wix/detox/instruments/Instruments.java
      539  2020-07-26 14:32   com/wix/detox/instruments/InstrumentsRecording.java
     2272  2020-07-26 14:32   com/wix/detox/instruments/DetoxInstrumentsManager.java
        0  2020-07-26 14:32   com/wix/detox/systeminfo/
     1428  2020-07-26 14:32   com/wix/detox/systeminfo/Environment.java
     4918  2020-07-26 14:32   com/wix/detox/LaunchIntentsFactory.kt
      736  2020-07-26 14:32   com/wix/detox/DetoxANRHandler.kt
     5187  2020-07-26 14:32   com/wix/detox/WebSocketClient.java
     6546  2020-07-26 14:32   com/wix/detox/DetoxActionHandlers.kt
      763  2020-07-26 14:32   com/wix/detox/DetoxCrashHandler.kt
        0  2020-07-26 14:32   com/wix/detox/reactnative/
        0  2020-07-26 14:32   com/wix/detox/reactnative/idlingresources/
     7407  2020-07-26 14:32   com/wix/detox/reactnative/idlingresources/AnimatedModuleIdlingResource.java
     3264  2020-07-26 14:32   com/wix/detox/reactnative/idlingresources/NetworkIdlingResource.java
     1940  2020-07-26 14:32   com/wix/detox/reactnative/idlingresources/BridgeIdlingResource.java
      990  2020-07-26 14:32   com/wix/detox/reactnative/idlingresources/NetworkingModuleReflected.kt
        0  2020-07-26 14:32   com/wix/detox/reactnative/idlingresources/timers/
      629  2020-07-26 14:32   com/wix/detox/reactnative/idlingresources/timers/IdleInterrogationStrategy.kt
     3715  2020-07-26 14:32   com/wix/detox/reactnative/idlingresources/timers/DefaultIdleInterrogationStrategy.kt
     2285  2020-07-26 14:32   com/wix/detox/reactnative/idlingresources/timers/DelegatedIdleInterrogationStrategy.kt
     1566  2020-07-26 14:32   com/wix/detox/reactnative/idlingresources/timers/TimersIdlingResource.kt
     5063  2020-07-26 14:32   com/wix/detox/reactnative/idlingresources/UIModuleIdlingResource.java
     5860  2020-07-26 14:32   com/wix/detox/reactnative/ReactNativeIdlingResources.kt
     4618  2020-07-26 14:32   com/wix/detox/reactnative/ReactNativeExtension.kt
      493  2020-07-26 14:32   com/wix/detox/reactnative/ReactNativeReloader.kt
      977  2020-07-26 14:32   com/wix/detox/reactnative/ReactNativeInfo.kt
     3208  2020-07-26 14:32   com/wix/detox/reactnative/ReactNativeLoadingMonitor.kt
     5751  2020-07-26 14:32   com/wix/detox/DetoxManager.java
     3502  2020-07-26 14:32   com/wix/detox/Delegator.java
        0  2020-07-26 14:32   com/wix/detox/common/
      189  2020-07-26 14:32   com/wix/detox/common/TextFileReader.kt
      465  2020-07-26 14:32   com/wix/detox/common/RNAnnotations.kt
     1132  2020-07-26 14:32   com/wix/detox/common/ViewScreenshot.kt
     1657  2020-07-26 14:32   com/wix/detox/common/JsonConverter.kt
      156  2020-07-26 14:32   com/wix/detox/common/SDKSupports.kt
        0  2020-07-26 14:32   com/wix/detox/uiautomator/
      372  2020-07-26 14:32   com/wix/detox/uiautomator/UiAutomator.java
     1851  2020-07-26 14:32   com/wix/detox/LaunchArgs.java
        0  2020-07-26 14:32   com/wix/detox/espresso/
     2788  2020-07-26 14:32   com/wix/detox/espresso/DetoxAssertion.java
        0  2020-07-26 14:32   com/wix/detox/espresso/action/
     1955  2020-07-26 14:32   com/wix/detox/espresso/action/RNClickAction.java
      914  2020-07-26 14:32   com/wix/detox/espresso/action/TakeViewScreenshotAction.kt
     3444  2020-07-26 14:32   com/wix/detox/espresso/action/DetoxSingleTap.kt
     1565  2020-07-26 14:32   com/wix/detox/espresso/action/DetoxMultiTap.kt
     1109  2020-07-26 14:32   com/wix/detox/espresso/action/DetoxTypeTextAction.java
        0  2020-07-26 14:32   com/wix/detox/espresso/assertion/
     2439  2020-07-26 14:32   com/wix/detox/espresso/assertion/ViewAssertions.java
      638  2020-07-26 14:32   com/wix/detox/espresso/DetoxErrors.java
       89  2020-07-26 14:32   com/wix/detox/espresso/ActionWithResult.kt
     5437  2020-07-26 14:32   com/wix/detox/espresso/UiAutomatorHelper.java
        0  2020-07-26 14:32   com/wix/detox/espresso/common/
     1150  2020-07-26 14:32   com/wix/detox/espresso/common/DetoxViewConfiguration.kt
     1971  2020-07-26 14:32   com/wix/detox/espresso/common/MotionEvents.kt
        0  2020-07-26 14:32   com/wix/detox/espresso/common/annot/
      627  2020-07-26 14:32   com/wix/detox/espresso/common/annot/MotionDefs.kt
    10045  2020-07-26 14:32   com/wix/detox/espresso/DetoxAction.java
     6494  2020-07-26 14:32   com/wix/detox/espresso/EspressoDetox.java
        0  2020-07-26 14:32   com/wix/detox/espresso/matcher/
     1690  2020-07-26 14:32   com/wix/detox/espresso/matcher/ViewMatchers.kt
      716  2020-07-26 14:32   com/wix/detox/espresso/matcher/ViewAtIndexMatcher.kt
     2075  2020-07-26 14:32   com/wix/detox/espresso/matcher/NullableTypeSafeMatcher.java
        0  2020-07-26 14:32   com/wix/detox/espresso/scroll/
     3153  2020-07-26 14:32   com/wix/detox/espresso/scroll/FlinglessSwiper.kt
      218  2020-07-26 14:32   com/wix/detox/espresso/scroll/DetoxSwiper.kt
      103  2020-07-26 14:32   com/wix/detox/espresso/scroll/ScrollEdgeException.kt
     2585  2020-07-26 14:32   com/wix/detox/espresso/scroll/ScrollProbes.kt
     1660  2020-07-26 14:32   com/wix/detox/espresso/scroll/DetoxSwipe.kt
    10602  2020-07-26 14:32   com/wix/detox/espresso/scroll/ScrollHelper.java
     3513  2020-07-26 14:32   com/wix/detox/espresso/DetoxMatcher.java
      685  2020-07-26 14:32   com/wix/detox/espresso/DetoxViewActions.java
        0  2020-07-26 14:32   org/
        0  2020-07-26 14:32   org/joor/
     1615  2020-07-26 14:32   org/joor/ReflectException.java
    27502  2020-07-26 14:32   org/joor/Reflect.java
---------                     -------
   213029                     102 files
```

**Comment by Tommos0** [comment]
Removing all references to `config` makes the build run.
```java
// Replace this with your app's package
package com.example;

import com.wix.detox.Detox;
// import com.wix.detox.config.DetoxConfig;

import org.junit.Rule;
import org.junit.Test;
import org.junit.runner.RunWith;

import androidx.test.ext.junit.runners.AndroidJUnit4;
import androidx.test.filters.LargeTest;
import androidx.test.rule.ActivityTestRule;

@RunWith(AndroidJUnit4.class)
@LargeTest
public class DetoxTest {
    @Rule
    // Replace 'MainActivity' with the value of android:name entry in 
    // <activity> in AndroidManifest.xml
    public ActivityTestRule<MainActivity> mActivityRule = new ActivityTestRule<>(MainActivity.class, false, false);

    @Test
    public void runDetoxTests() {
        // DetoxConfig detoxConfig = new DetoxConfig();
        // detoxConfig.idlePolicyConfig.masterTimeoutSec = 90;
        // detoxConfig.idlePolicyConfig.idleResourceTimeoutSec = 60;
        // detoxConfig.rnContextLoadTimeoutSec = (com.example.BuildConfig.DEBUG ? 180 : 60);

        // Detox.runTests(mActivityRule, detoxConfig);
        Detox.runTests(mActivityRule);
    }
}
```

**Comment by d4vidi** [comment]
@Tommos0 Really sorry, seems you've fallen in between the very small gap of pushing code and releasing it! You can apply your own config with Detox `17.3.2` (not `17.3.1`), but it's really not mandatory. lmk if fixed.

**Comment by Tommos0** [comment]
No worries :). Fixed with 17.3.2 :+1:

**Comment by whalemare** [comment]
In my case, I should change order in `build.gradle` for searching `Detox` lib localy and after that in other places. So my config look like that:

```
allprojects {
    repositories {
        mavenLocal()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }
        
        // Detox
        maven {
          url "$rootDir/../node_modules/detox/Detox-android"
        }

        google()
        jcenter()
        maven { url 'https://www.jitpack.io' }
    }
}
```

**Comment by sourabhAfunky** [comment]
@d4vidi I am facing the exact @Tommos0 issue I have gone through official documentation several times for an android setup. I have kept all required installation methods but getting the same issue while building on a "physical" device 

- config for physical device

on .detoxrc.json
`- "emulator": {
      "type": "android.attached",
      "device": {
        "adbName":"adbName"
      }
    }

"configurations": {
    "ios": {
      "device": "simulator",
      "app": "ios"
    },
    "android.emu.debug": {
      "device": "emulator",
      "app": "android.debug"
    },
    "android.emu.release": {
      "device": "emulator",
      "app": "android.release"
    }
  }
`
DetoxTest.java path is

- android/app/src/androidTest/java/com/com.ProjectName/DetoxTest.java

errors
`error: cannot find symbol
    public ActivityTestRule<MainActivity> mActivityRule = new ActivityTestRule<>(MainActivity.class, false, false);
                            ^
  symbol:   class MainActivity
  location: class DetoxTest`

`cannot find symbol
    public ActivityTestRule<MainActivity> mActivityRule = new ActivityTestRule<>(MainActivity.class, false, false);
                                                                                 ^
  symbol:   class MainActivity
  location: class DetoxTest`

`cannot find symbol
        Detox.runTests(mActivityRule, detoxConfig);
                                      ^
  symbol:   variable detoxConfig
  location: class DetoxTest`

**Comment by d4vidi** [comment]
@sourabhAfunky `android/app/src/androidTest/java/com/com.ProjectName/DetoxTest.java` doesn't seem right (`com.ProjectName` in particular). For an imaginary app called `funky` -- defined under the `com.funky` package ID, you must use this path: `android/app/src/androidTest/java/com/funky/DetoxTest.java`

Be sure to use our example app as a reference: https://github.com/wix/Detox/tree/master/examples/demo-react-native/android/app/src/androidTest/java/com/example

Putting `DetoxTest.java` in the wrong directory keeps the Android build from properly looking up `MainActivity` - as in your case.

**Comment by sourabhAfunky** [comment]
> @sourabhAfunky `android/app/src/androidTest/java/com/com.ProjectName/DetoxTest.java` doesn't seem right (`com.ProjectName` in particular). For an imaginary app called `funky` -- defined under the `com.funky` package ID, you must use this path: `android/app/src/androidTest/java/com/funky/DetoxTest.java`
> 
> Be sure to use our example app as a reference: https://github.com/wix/Detox/tree/master/examples/demo-react-native/android/app/src/androidTest/java/com/example
> 
> Putting `DetoxTest.java` in the wrong directory keeps the Android build from properly looking up `MainActivity` - as in your case.

@d4vidi yes Previously I implemented your mentioned directory structure but the error was the same

**Comment by arielma77** [comment]
I am having the exact same issue, I followed the documentation, tried a couple of "magical solutions" but the issue is still showing up. I someone found the solution already, could share it here please?

**Comment by arielmachado-uy** [comment]
Hi @bruteforks, thank you so much for your response!

The only thing that worked for me was to add the section "allprojects" to the build.gradle file under "android"
I read that in the docs, but since I already had a section called "repositories" I didn't think it was necessary. It turned out that it was necessary (I kept both)

Thank you again for taking the time to answer and helping me and the community

**Comment by aravindMylsamy** [comment]
> @arielma77 I fixed the problem in a couple ways. one was my detoxTest.java wasn't under androidTest folder like in the docs. Another issue was not putting the allprojects {} config in the right place. see code from android/build.gradle:
> 
> ```
>  buildscript {
>     ext {
>         buildToolsVersion = "33.0.0"
>         minSdkVersion = 21
>         compileSdkVersion = 33
>         targetSdkVersion = 33
>         kotlinVersion = '1.8.0' // detox setup
> 
>         // We use NDK 23 which has both M1 support and is the side-by-side NDK version from AGP.
>         ndkVersion = "23.1.7779620"
>     }
>     repositories {
>         google()
>         mavenCentral()
>     }
>     dependencies {
>         classpath('com.android.tools.build:gradle:7.4.1')
>         classpath("com.facebook.react:react-native-gradle-plugin")
>         classpath('com.google.gms:google-services:4.3.15')
>         classpath('com.google.firebase:firebase-crashlytics-gradle:2.9.4')
>         classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion") // detox setup
>     }
> }
> 
> allprojects { // (4)
>     repositories {
>         maven {
>           url("$rootDir/../node_modules/detox/Detox-android")
>         }
>     }
> }
> ```
> 
> I also did this from another issue, but I can't remember if it helped fix the problem, as I tried many fixes. under app/build.gradle in dependencies {} section
> 
> ```
>     androidTestImplementation('com.wix:detox:+') {
>         exclude module: "protobuf-lite"
>     }
> ```
> 
> Let me know if this fixes, as I may have done some other hacks.

Not fixing
