### ISSUE TITLE
Detox can't seem to connect to the test app on android

### ISSUE THREAD

**Issue by dincho-kostadinov** [wix/Detox#3233]
`
14:53:08.688 detox[11120] ERROR: [APP_UNREACHABLE] Detox can't seem to connect to the test app(s)!

HINT:

The test app might have crashed prematurely, or has had trouble setting up the connection.
Refer to our troubleshooting guide, for full details: https://wix.github.io/Detox/docs/troubleshooting/running-tests#tests-execution-hangs

14:53:08.698 detox[11120] DEBUG: [WSS_CLOSE] Detox server has been closed gracefully
FAIL e2e/firstTest.e2e.js (10.76 s)
  Example
    × should have welcome screen (2 ms)

  ● Example › should have welcome screen

    DetoxRuntimeError: Failed to run application on the device

    HINT: Most likely, your tests have timed out and called detox.cleanup() while it was waiting for "ready" message (over WebSocket) from the instrumentation process.

      1 | describe('Example', () => {
      2 |   beforeAll(async () => {
    > 3 |     await device.launchApp({ newInstance: true });
        |                  ^
      4 |   });
      5 |
      6 |   beforeEach(async () => {

      at createErrorWithUserStack (../node_modules/detox/src/utils/errorUtils.js:33:27)
      at RuntimeDevice.launchApp (../node_modules/detox/src/utils/wrapWithStackTraceCutter.js:9:34)
      at _callee$ (firstTest.e2e.js:3:18)
      at tryCatch (../node_modules/regenerator-runtime/runtime.js:63:40)
      at Generator.invoke [as _invoke] (../node_modules/regenerator-runtime/runtime.js:293:22)
      at Generator.next (../node_modules/regenerator-runtime/runtime.js:118:21)
      at tryCatch (../node_modules/regenerator-runtime/runtime.js:63:40)
      at invoke (../node_modules/regenerator-runtime/runtime.js:154:20)
      at ../node_modules/regenerator-runtime/runtime.js:189:11
      at callInvokeWithMethodAndArg (../node_modules/regenerator-runtime/runtime.js:188:16)
      at AsyncIterator.enqueue (../node_modules/regenerator-runtime/runtime.js:211:13)
      at AsyncIterator.next (../node_modules/regenerator-runtime/runtime.js:118:21)
      at Object.<anonymous>.exports.async (../node_modules/regenerator-runtime/runtime.js:238:14)
      at _callee (firstTest.e2e.js:2:13)

14:53:08.849 detox[3524] ERROR: [cli.js] Command failed: jest --config e2e/config.json --testNamePattern '^((?!:ios:).)*$' e2e
`

I got this message when I try to run the tests on android environment . Any ideas or solution? 
Thanks in advance!

Versions: 
```
 "detox": "^19.4.5",
  "jest": "^26.6.3",
 "react-native": "0.64.2",
```

_Originally posted by @dincho-kostadinov in https://github.com/wix/Detox/issues/3050#issuecomment-1048755937_

**Comment by humaidk2** [comment]
If you have flipper installed, maybe you could try disabling it, it fixed it for me.

But probably, you would be better off checking android studio logs for errors

**Comment by dincho-kostadinov** [comment]
@humaidk2  thanks for the info bu I dont have flipper . I fixed this problem with some changes in the DetoxTest.java class that I created. It looks like this: 
`package com.nameOfTheProject;

import com.wix.detox.Detox;
import com.wix.detox.config.DetoxConfig;

import org.junit.Rule;
import org.junit.Test;
import org.junit.runner.RunWith;

import androidx.test.ext.junit.runners.AndroidJUnit4;
import androidx.test.filters.LargeTest;
import androidx.test.rule.ActivityTestRule;

@RunWith(AndroidJUnit4.class)
@LargeTest
public class DetoxTest {
    @Rule
    public ActivityTestRule<MainActivity> mActivityRule = new ActivityTestRule<>(MainActivity.class, false, false);

    @Test
    public void runDetoxTests() {

        DetoxConfig detoxConfig = new DetoxConfig();
        detoxConfig.idlePolicyConfig.masterTimeoutSec = 90;
        detoxConfig.idlePolicyConfig.idleResourceTimeoutSec = 60;
        detoxConfig.rnContextLoadTimeoutSec = (com.nameOfTheProject.BuildConfig.DEBUG ? 180 : 60);

        Detox.runTests(mActivityRule, detoxConfig);
    }
}`

**Comment by Tuliiiii** [comment]
I am still facing the same issue "Detox can't seem to connect to the test app on android". Can someone please help me with the solution?

**Comment by HauLe17** [comment]
the same issue still happen, have any solution for this?

**Comment by Mkay4real** [comment]
I'm facing the same issue. What's the way out?

**Comment by Younext19** [comment]
have you started your server before ? x')
