### ISSUE TITLE
I'm getting an error when trying to run tests

### ISSUE THREAD

**Issue by henrique-in** [wix/Detox#3378]
### Description

I'm trying to integrate some e2e tests into my react native (expo bare) mobile project. I'm following the instructions found on the detox [Getting Started](https://wix.github.io/Detox/docs/introduction/getting-started) page. I'm able to successfully build my project, but everytime I attempt the detox test command:

detox test --configuration ios.sim.debug

**I get the following error:**

FAIL  e2e/firstTest.e2e.jsrun...
  ● Test suite failed to run

    TypeError: Class extends value #<Object> is not a constructor or null

      at Object.<anonymous> (../node_modules/detox/runners/jest-circus/environment.js:24:38)
      at Object.newLoader (../node_modules/pirates/lib/index.js:141:7)
      at Object.<anonymous> (../node_modules/detox/runners/jest-circus/index.js:4:32)

09:07:59.324 detox[21032] ERROR: [cli.js] Command failed: jest --config e2e/config.json --testNamePattern '^((?!:android:).)*$' e2e

**Configs:**

**package.json**

...
"detox": "^19.6.2"
"jest": "^27.0.0",
"jest-circus": "^27.5.1",
...

**./e2e/config.json**

{
  "testEnvironment": "./environment",
  "testRunner": "jest-circus/runner",
  "testTimeout": 120000,
  "testRegex": "\\.e2e\\.js$",
  "reporters": ["detox/runners/jest/streamlineReporter"],
  "verbose": true
}

**./e2e/environment.js**

const {
  DetoxCircusEnvironment,
  SpecReporter,
  WorkerAssignReporter,
} = require('detox/runners/jest-circus');

class CustomDetoxEnvironment extends DetoxCircusEnvironment {
  constructor(config, context) {
    super(config, context);

    // Can be safely removed, if you are content with the default value (=300000ms)
    this.initTimeout = 300000;

    // This takes care of generating status logs on a per-spec basis. By default, Jest only reports at file-level.
    // This is strictly optional.
    this.registerListeners({
      SpecReporter,
      WorkerAssignReporter,
    });
  }
}

module.exports = CustomDetoxEnvironment;

### Your environment

Detox version:  19.6.7
React Native version: 0.64.3 
Node version: 14.19.0
Device model: iPhone 11 or Pixel 3 API 28
OS: mac os monterrey
Test-runner (select one): jest-circus / jest+jasmine / mocha / other

**Comment by stefanocdn** [comment]
Same here

**Comment by joseluissb** [comment]
Hello, I got the same problem and I fixed it by downgrading to Jest 27. Hope it helps!

**Comment by joseluissb** [comment]
It seems you are passing an invalid object into the "beforeEach", but it looks unrelated to the incompatibility with Jest 28.

**Comment by henrique-in** [comment]
,Thank you, get it resolved

**Comment by noomorph** [comment]
@henrique-in, indeed, the latest Detox version should fix the issue.

**Comment by nidhisachan** [comment]
I am still getting the same issue even though I downgraded the version to 27.

**Comment by developerdevsoni** [comment]
same 
describe('Example', () => {
  beforeAll(async () => {
    await device.launchApp();
  });

  beforeEach(async () => {
    await device.reloadReactNative();
  });

  it('should have welcome screen', async () => {
    await expect(element(by.id('welcome'))).toBeVisible();
  });

  it('should show hello screen after tap', async () => {
    await element(by.id('hello_button')).tap();
    await expect(element(by.text('Hello!!!'))).toBeVisible();
  });

  it('should show world screen after tap', async () => {
    await element(by.id('world_button')).tap();
    await expect(element(by.text('World!!!'))).toBeVisible();
  });
});



this is my basic test case. do anyone know the issue 



library

  "detox": "^19.13.0",
    "eslint": "6.8.0",
    "jest": "27.5.1",
    "jest-circus": "27.5.1",
    "jest-environment-jsdom": "27.5.1",
