### ISSUE TITLE
Error `The operation couldn’t be completed. found nothing to terminate`

### ISSUE THREAD

**Issue by Peter-Cumming** [wix/Detox#3518]
### What happened?

I am currently validating an app against XCode14 BETA against iPadOS16. 

On executing the Detox test run:  `detox test -l verbose --record-logs failing --configuration ios`

The Detox connection is registered successfully, `applesimutils` identifies the device and starts the simulator successfully. The specified app is terminated and then uninstalled successfully but then Detox appears to be trying to terminate the app a 2nd time (note this is after the app has been successfully uninstalled). 

<img width="1291" alt="Screenshot 2022-07-28 at 15 36 21" src="https://user-images.githubusercontent.com/12497755/181745823-aea0c73f-4cbb-482e-93f0-dedd6f9e40ba.png">

The result is an error below.

> 15:19:27.425 detox[57551] DEBUG: [EXEC_FAIL, #5] "/usr/bin/xcrun simctl terminate 091E1685-48CC-4D6A-A049-896D552BBF55 com.hudl.replay" failed with error = ChildProcessError: Command failed: /usr/bin/xcrun simctl terminate 091E1685-48CC-4D6A-A049-896D552BBF55 com.hudl.replay
> An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=3):
> The operation couldn’t be completed. found nothing to terminate
> found nothing to terminate
>  `/usr/bin/xcrun simctl terminate 091E1685-48CC-4D6A-A049-896D552BBF55 com.hudl.replay` (exited with error code 3) (code=3), stdout and stderr:

I can see there is a work around already in Detox repo [here](https://github.com/wix/Detox/blob/9229e64ec8f95574aab5beeeb4fa6bcc84844f69/detox/src/devices/common/drivers/ios/tools/AppleSimUtils.js#L239-L255) for a v.similar sounding issue. The error message is subtly different  `found nothing to terminate` and therefore not handled. I'm not sure whether this is a new error message in the latest version of XCode or a new error but from the comments it  

```
// Since we have no convenient way to check whether the app is currently running or not, we might execute this
      // command (terminate) even if the app is not currently running, or even installed.
      // We have encountered some case where the following error is thrown in a case where the app did not run:
      // ```
      // An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=3):
      // Application termination failed.
      // FBSSystemService reported failure without an error, possibly because the app is not currently running.
      // ```
      // This workaround is done to ignore the error above, as we do not care if the app was running before, we just
      // want to make sure it isn't now.
      if (err.code === 3 && err.stderr.includes(`the app is not currently running`)) {
        return;
      }


      throw err;
    }
  }
```

Modifying this to account for the new wording ensures that Detox runs as expected.

### What was the expected behaviour?

Once the Detox connection has registered, applesimutils has identified the device and booted the simulator. The app should be terminated and then successfully uninstalled. Once confirmed the app should be installed and the tests run.

[EXEC_CMD, 0] - List simulator devices by Type
[EXEC_CMD, 1] - List simulator devices by ID
[EXEC_CMD, 2] - Terminate the app running on the device
[EXEC_CMD, 3] - Uninstall the app running on the device
[EXEC_CMD, 4] - Install the app on the device
[EXEC_CMD, 5] - Run the tests

### Was it tested on latest Detox?

- [ ] I have tested this issue on the latest Detox release and it still reproduces.

### In what environment did this happen?

Detox version:  19.7.1
React Native version:  "0.67.4"
Node version:  v16.4.2
Test-runner (select one): jest-circus

### Detox logs

<details><summary>Detox logs</summary>

```
peter.cumming@HUD040089 ios % yarn e2e-run adminModal.e2e.ts --loglevel trace
➤ YN0000: executing [e2e-run]: detox test -l verbose --record-logs failing --take-screenshots failing --record-videos failing --configuration ios
12:12:59.491 detox[85895] INFO:  [test.js] DETOX_CONFIGURATION="ios" DETOX_LOGLEVEL="trace" DETOX_RECORD_LOGS="failing" DETOX_RECORD_VIDEOS="failing" DETOX_REPORT_SPECS=true DETOX_START_TIMESTAMP=1659093179488 DETOX_TAKE_SCREENSHOTS="failing" DETOX_USE_CUSTOM_LOGGER=true jest --config e2e/config.json --testNamePattern '^((?!:android:).)*$' --maxWorkers 1 adminModal.e2e.ts
watchman warning:  Recrawled this watch 145 times, most recently because:
MustScanSubDirs UserDroppedTo resolve, please review the information on
https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
To clear this warning, run:
`watchman watch-del '/Users/peter.cumming/COMPANY_Repos/PRODUCT-mobile' ; watchman watch-project '/Users/peter.cumming/COMPANY_Repos/PRODUCT-mobile'`

12:13:00.533 detox[85896] TRACE: [DETOX_CREATE] created a Detox instance with config:
{
  appsConfig: {
    default: {
      type: 'ios.app',
      binaryPath: './ios/build/Build/Products/Debug-iphonesimulator/PRODUCT.app',
      build: 'cd ios && xcodebuild -workspace PRODUCT.xcworkspace -scheme PRODUCT -configuration Debug -sdk iphonesimulator -derivedDataPath build'
    }
  },
  artifactsConfig: {
    rootDir: 'artifacts/ios.2022-07-29 11-12-59Z',
    plugins: {
      log: {
        enabled: true,
        keepOnlyFailedTestsArtifacts: true
      },
      screenshot: {
        enabled: true,
        shouldTakeAutomaticSnapshots: true,
        keepOnlyFailedTestsArtifacts: true
      },
      video: {
        enabled: true,
        keepOnlyFailedTestsArtifacts: true
      },
      instruments: {
        enabled: false,
        keepOnlyFailedTestsArtifacts: false
      },
      timeline: {
        enabled: false
      },
      uiHierarchy: {
        enabled: false,
        keepOnlyFailedTestsArtifacts: false
      }
    },
    pathBuilder: ArtifactPathBuilder {
      _rootDir: 'artifacts/ios.2022-07-29 11-12-59Z'
    }
  },
  behaviorConfig: {
    init: {
      reinstallApp: true,
      exposeGlobals: true
    },
    cleanup: {
      shutdownDevice: true
    },
    launchApp: 'auto'
  },
  cliConfig: {
    recordLogs: 'failing',
    takeScreenshots: 'failing',
    recordVideos: 'failing',
    configuration: 'ios',
    loglevel: 'trace',
    useCustomLogger: true
  },
  configurationName: 'ios',
  deviceConfig: {
    type: 'ios.simulator',
    device: {
      type: 'iPad Pro (12.9-inch) (5th generation)'
    }
  },
  runnerConfig: {
    testRunner: 'jest',
    runnerConfig: 'e2e/config.json',
    specs: 'e2e',
    skipLegacyWorkersInjection: false
  },
  sessionConfig: {
    autoStart: true,
    sessionId: 'f8e7e827-c480-fa70-2b4e-8cf44f869d2c',
    debugSynchronization: 10000
  }
}
12:13:00.535 detox[85896] DEBUG: [WSS_CREATE] Detox server listening on localhost:64012...
12:13:00.540 detox[85896] DEBUG: [WSS_CONNECTION, #64013] registered a new connection.
12:13:00.541 detox[85896] TRACE: [WS_OPEN] opened web socket to: ws://localhost:64012
12:13:00.542 detox[85896] TRACE: [WS_SEND] {"type":"login","params":{"sessionId":"f8e7e827-c480-fa70-2b4e-8cf44f869d2c","role":"tester"},"messageId":0}
12:13:00.543 detox[85896] TRACE: [WSS_GET_FROM, #64013] {"type":"login","params":{"sessionId":"f8e7e827-c480-fa70-2b4e-8cf44f869d2c","role":"tester"},"messageId":0}
12:13:00.543 detox[85896] TRACE: [SESSION_CREATED] created session f8e7e827-c480-fa70-2b4e-8cf44f869d2c
12:13:00.543 detox[85896] TRACE: [WSS_SEND_TO, #tester] {"type":"loginSuccess","params":{"testerConnected":true,"appConnected":false},"messageId":0}
12:13:00.543 detox[85896] TRACE: [SESSION_JOINED] tester joined session f8e7e827-c480-fa70-2b4e-8cf44f869d2c
12:13:00.543 detox[85896] TRACE: [WS_MESSAGE] {"type":"loginSuccess","params":{"testerConnected":true,"appConnected":false},"messageId":0}
 
12:13:00.827 detox[85896] DEBUG: [EXEC_CMD, #0] applesimutils --list --byType "iPad Pro (12.9-inch) (5th generation)"
12:13:01.089 detox[85896] TRACE: [EXEC_SUCCESS, #0] [
  {
    "isAvailable" : true,
    "logPath" : "\/Users\/peter.cumming\/Library\/Logs\/CoreSimulator\/091E1685-48CC-4D6A-A049-896D552BBF55",
    "logPathSize" : 446464,
    "state" : "Booted",
    "name" : "iPad Pro (12.9-inch) (5th generation)",
    "dataPathSize" : 4695343104,
    "deviceType" : {
      "maxRuntimeVersion" : 4294967295,
      "bundlePath" : "\/Applications\/Xcode-14.0.0-Beta.app\/Contents\/Developer\/Platforms\/iPhoneOS.platform\/Library\/Developer\/CoreSimulator\/Profiles\/DeviceTypes\/iPad Pro (12.9-inch) (5th generation).simdevicetype",
      "maxRuntimeVersionString" : "65535.255.255",
      "name" : "iPad Pro (12.9-inch) (5th generation)",
      "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPad-Pro-12-9-inch-5th-generation",
      "productFamily" : "iPad",
      "modelIdentifier" : "iPad13,10",
      "minRuntimeVersionString" : "14.5.0",
      "minRuntimeVersion" : 918784
    },
    "os" : {
      "bundlePath" : "\/Applications\/Xcode-14.0.0-Beta.app\/Contents\/Developer\/Platforms\/iPhoneOS.platform\/Library\/Developer\/CoreSimulator\/Profiles\/Runtimes\/iOS.simruntime",
      "buildversion" : "20A5283p",
      "platform" : "iOS",
      "runtimeRoot" : "\/Applications\/Xcode-14.0.0-Beta.app\/Contents\/Developer\/Platforms\/iPhoneOS.platform\/Library\/Developer\/CoreSimulator\/Profiles\/Runtimes\/iOS.simruntime\/Contents\/Resources\/RuntimeRoot",
      "identifier" : "com.apple.CoreSimulator.SimRuntime.iOS-16-0",
      "version" : "16.0",
      "isInternal" : false,
      "isAvailable" : true,
      "name" : "iOS 16.0",
      "supportedDeviceTypes" : [
        {
          "bundlePath" : "\/Applications\/Xcode-14.0.0-Beta.app\/Contents\/Developer\/Platforms\/iPhoneOS.platform\/Library\/Developer\/CoreSimulator\/Profiles\/DeviceTypes\/iPhone 8.simdevicetype",
          "name" : "iPhone 8",
          "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPhone-8",
          "productFamily" : "iPhone"
        },
        {
          "bundlePath" : "\/Applications\/Xcode-14.0.0-Beta.app\/Contents\/Developer\/Platforms\/iPhoneOS.platform\/Library\/Developer\/CoreSimulator\/Profiles\/DeviceTypes\/iPhone 8 Plus.simdevicetype",
          "name" : "iPhone 8 Plus",
          "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPhone-8-Plus",
          "productFamily" : "iPhone"
        },
        {
          "bundlePath" : "\/Applications\/Xcode-14.0.0-Beta.app\/Contents\/Developer\/Platforms\/iPhoneOS.platform\/Library\/Developer\/CoreSimulator\/Profiles\/DeviceTypes\/iPhone X.simdevicetype",
          "name" : "iPhone X",
          "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPhone-X",
          "productFamily" : "iPhone"
        },
        {
          "bundlePath" : "\/Applications\/Xcode-14.0.0-Beta.app\/Contents\/Developer\/Platforms\/iPhoneOS.platform\/Library\/Developer\/CoreSimulator\/Profiles\/DeviceTypes\/iPhone Xs.simdevicetype",
          "name" : "iPhone Xs",
          "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPhone-XS",
          "productFamily" : "iPhone"
        },
        {
          "bundlePath" : "\/Applications\/Xcode-14.0.0-Beta.app\/Contents\/Developer\/Platforms\/iPhoneOS.platform\/Library\/Developer\/CoreSimulator\/Profiles\/DeviceTypes\/iPhone Xs Max.simdevicetype",
          "name" : "iPhone Xs Max",
          "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPhone-XS-Max",
          "productFamily" : "iPhone"
        },
        {
          "bundlePath" : "\/Applications\/Xcode-14.0.0-Beta.app\/Contents\/Developer\/Platforms\/iPhoneOS.platform\/Library\/Developer\/CoreSimulator\/Profiles\/DeviceTypes\/iPhone Xʀ.simdevicetype",
          "name" : "iPhone Xʀ",
          "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPhone-XR",
          "productFamily" : "iPhone"
        },
        {
          "bundlePath" : "\/Applications\/Xcode-14.0.0-Beta.app\/Contents\/Developer\/Platforms\/iPhoneOS.platform\/Library\/Developer\/CoreSimulator\/Profiles\/DeviceTypes\/iPhone 11.simdevicetype",
          "name" : "iPhone 11",
          "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPhone-11",
          "productFamily" : "iPhone"
        },
        {
          "bundlePath" : "\/Applications\/Xcode-14.0.0-Beta.app\/Contents\/Developer\/Platforms\/iPhoneOS.platform\/Library\/Developer\/CoreSimulator\/Profiles\/DeviceTypes\/iPhone 11 Pro.simdevicetype",
          "name" : "iPhone 11 Pro",
          "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPhone-11-Pro",
          "productFamily" : "iPhone"
        },
        {
          "bundlePath" : "\/Applications\/Xcode-14.0.0-Beta.app\/Contents\/Developer\/Platforms\/iPhoneOS.platform\/Library\/Developer\/CoreSimulator\/Profiles\/DeviceTypes\/iPhone 11 Pro Max.simdevicetype",
          "name" : "iPhone 11 Pro Max",
          "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPhone-11-Pro-Max",
          "productFamily" : "iPhone"
        },
        {
          "bundlePath" : "\/Applications\/Xcode-14.0.0-Beta.app\/Contents\/Developer\/Platforms\/iPhoneOS.platform\/Library\/Developer\/CoreSimulator\/Profiles\/DeviceTypes\/iPhone SE (2nd generation).simdevicetype",
          "name" : "iPhone SE (2nd generation)",
          "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPhone-SE--2nd-generation-",
          "productFamily" : "iPhone"
        },
        {
          "bundlePath" : "\/Applications\/Xcode-14.0.0-Beta.app\/Contents\/Developer\/Platforms\/iPhoneOS.platform\/Library\/Developer\/CoreSimulator\/Profiles\/DeviceTypes\/iPhone 12 mini.simdevicetype",
          "name" : "iPhone 12 mini",
          "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPhone-12-mini",
          "productFamily" : "iPhone"
        },
        {
          "bundlePath" : "\/Applications\/Xcode-14.0.0-Beta.app\/Contents\/Developer\/Platforms\/iPhoneOS.platform\/Library\/Developer\/CoreSimulator\/Profiles\/DeviceTypes\/iPhone 12.simdevicetype",
          "name" : "iPhone 12",
          "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPhone-12",
          "productFamily" : "iPhone"
        },
        {
          "bundlePath" : "\/Applications\/Xcode-14.0.0-Beta.app\/Contents\/Developer\/Platforms\/iPhoneOS.platform\/Library\/Developer\/CoreSimulator\/Profiles\/DeviceTypes\/iPhone 12 Pro.simdevicetype",
          "name" : "iPhone 12 Pro",
          "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPhone-12-Pro",
          "productFamily" : "iPhone"
        },
        {
          "bundlePath" : "\/Applications\/Xcode-14.0.0-Beta.app\/Contents\/Developer\/Platforms\/iPhoneOS.platform\/Library\/Developer\/CoreSimulator\/Profiles\/DeviceTypes\/iPhone 12 Pro Max.simdevicetype",
          "name" : "iPhone 12 Pro Max",
          "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPhone-12-Pro-Max",
          "productFamily" : "iPhone"
        },
        {
          "bundlePath" : "\/Applications\/Xcode-14.0.0-Beta.app\/Contents\/Developer\/Platforms\/iPhoneOS.platform\/Library\/Developer\/CoreSimulator\/Profiles\/DeviceTypes\/iPhone 13 Pro.simdevicetype",
          "name" : "iPhone 13 Pro",
          "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPhone-13-Pro",
          "productFamily" : "iPhone"
        },
        {
          "bundlePath" : "\/Applications\/Xcode-14.0.0-Beta.app\/Contents\/Developer\/Platforms\/iPhoneOS.platform\/Library\/Developer\/CoreSimulator\/Profiles\/DeviceTypes\/iPhone 13 Pro Max.simdevicetype",
          "name" : "iPhone 13 Pro Max",
          "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPhone-13-Pro-Max",
          "productFamily" : "iPhone"
        },
        {
          "bundlePath" : "\/Applications\/Xcode-14.0.0-Beta.app\/Contents\/Developer\/Platforms\/iPhoneOS.platform\/Library\/Developer\/CoreSimulator\/Profiles\/DeviceTypes\/iPhone 13 mini.simdevicetype",
          "name" : "iPhone 13 mini",
          "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPhone-13-mini",
          "productFamily" : "iPhone"
        },
        {
          "bundlePath" : "\/Applications\/Xcode-14.0.0-Beta.app\/Contents\/Developer\/Platforms\/iPhoneOS.platform\/Library\/Developer\/CoreSimulator\/Profiles\/DeviceTypes\/iPhone 13.simdevicetype",
          "name" : "iPhone 13",
          "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPhone-13",
          "productFamily" : "iPhone"
        },
        {
          "bundlePath" : "\/Applications\/Xcode-14.0.0-Beta.app\/Contents\/Developer\/Platforms\/iPhoneOS.platform\/Library\/Developer\/CoreSimulator\/Profiles\/DeviceTypes\/iPhone SE (3rd generation).simdevicetype",
          "name" : "iPhone SE (3rd generation)",
          "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPhone-SE-3rd-generation",
          "productFamily" : "iPhone"
        },
        {
          "bundlePath" : "\/Applications\/Xcode-14.0.0-Beta.app\/Contents\/Developer\/Platforms\/iPhoneOS.platform\/Library\/Developer\/CoreSimulator\/Profiles\/DeviceTypes\/iPad Pro (9.7-inch).simdevicetype",
          "name" : "iPad Pro (9.7-inch)",
          "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPad-Pro--9-7-inch-",
          "productFamily" : "iPad"
        },
        {
          "bundlePath" : "\/Applications\/Xcode-14.0.0-Beta.app\/Contents\/Developer\/Platforms\/iPhoneOS.platform\/Library\/Developer\/CoreSimulator\/Profiles\/DeviceTypes\/iPad Pro (12.9-inch) (1st generation).simdevicetype",
          "name" : "iPad Pro (12.9-inch) (1st generation)",
          "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPad-Pro",
          "productFamily" : "iPad"
        },
        {
          "bundlePath" : "\/Applications\/Xcode-14.0.0-Beta.app\/Contents\/Developer\/Platforms\/iPhoneOS.platform\/Library\/Developer\/CoreSimulator\/Profiles\/DeviceTypes\/iPad (5th generation).simdevicetype",
          "name" : "iPad (5th generation)",
          "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPad--5th-generation-",
          "productFamily" : "iPad"
        },
        {
          "bundlePath" : "\/Applications\/Xcode-14.0.0-Beta.app\/Contents\/Developer\/Platforms\/iPhoneOS.platform\/Library\/Developer\/CoreSimulator\/Profiles\/DeviceTypes\/iPad Pro (12.9-inch) (2nd generation).simdevicetype",
          "name" : "iPad Pro (12.9-inch) (2nd generation)",
          "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPad-Pro--12-9-inch---2nd-generation-",
          "productFamily" : "iPad"
        },
        {
          "bundlePath" : "\/Applications\/Xcode-14.0.0-Beta.app\/Contents\/Developer\/Platforms\/iPhoneOS.platform\/Library\/Developer\/CoreSimulator\/Profiles\/DeviceTypes\/iPad Pro (10.5-inch).simdevicetype",
          "name" : "iPad Pro (10.5-inch)",
          "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPad-Pro--10-5-inch-",
          "productFamily" : "iPad"
        },
        {
          "bundlePath" : "\/Applications\/Xcode-14.0.0-Beta.app\/Contents\/Developer\/Platforms\/iPhoneOS.platform\/Library\/Developer\/CoreSimulator\/Profiles\/DeviceTypes\/iPad (6th generation).simdevicetype",
          "name" : "iPad (6th generation)",
          "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPad--6th-generation-",
          "productFamily" : "iPad"
        },
        {
          "bundlePath" : "\/Applications\/Xcode-14.0.0-Beta.app\/Contents\/Developer\/Platforms\/iPhoneOS.platform\/Library\/Developer\/CoreSimulator\/Profiles\/DeviceTypes\/iPad (7th generation).simdevicetype",
          "name" : "iPad (7th generation)",
          "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPad--7th-generation-",
          "productFamily" : "iPad"
        },
        {
          "bundlePath" : "\/Applications\/Xcode-14.0.0-Beta.app\/Contents\/Developer\/Platforms\/iPhoneOS.platform\/Library\/Developer\/CoreSimulator\/Profiles\/DeviceTypes\/iPad Pro (11-inch) (1st generation).simdevicetype",
          "name" : "iPad Pro (11-inch) (1st generation)",
          "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPad-Pro--11-inch-",
          "productFamily" : "iPad"
        },
        {
          "bundlePath" : "\/Applications\/Xcode-14.0.0-Beta.app\/Contents\/Developer\/Platforms\/iPhoneOS.platform\/Library\/Developer\/CoreSimulator\/Profiles\/DeviceTypes\/iPad Pro (12.9-inch) (3rd generation).simdevicetype",
          "name" : "iPad Pro (12.9-inch) (3rd generation)",
          "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPad-Pro--12-9-inch---3rd-generation-",
          "productFamily" : "iPad"
        },
        {
          "bundlePath" : "\/Applications\/Xcode-14.0.0-Beta.app\/Contents\/Developer\/Platforms\/iPhoneOS.platform\/Library\/Developer\/CoreSimulator\/Profiles\/DeviceTypes\/iPad Pro (11-inch) (2nd generation).simdevicetype",
          "name" : "iPad Pro (11-inch) (2nd generation)",
          "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPad-Pro--11-inch---2nd-generation-",
          "productFamily" : "iPad"
        },
        {
          "bundlePath" : "\/Applications\/Xcode-14.0.0-Beta.app\/Contents\/Developer\/Platforms\/iPhoneOS.platform\/Library\/Developer\/CoreSimulator\/Profiles\/DeviceTypes\/iPad Pro (12.9-inch) (4th generation).simdevicetype",
          "name" : "iPad Pro (12.9-inch) (4th generation)",
          "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPad-Pro--12-9-inch---4th-generation-",
          "productFamily" : "iPad"
        },
        {
          "bundlePath" : "\/Applications\/Xcode-14.0.0-Beta.app\/Contents\/Developer\/Platforms\/iPhoneOS.platform\/Library\/Developer\/CoreSimulator\/Profiles\/DeviceTypes\/iPad mini (5th generation).simdevicetype",
          "name" : "iPad mini (5th generation)",
          "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPad-mini--5th-generation-",
          "productFamily" : "iPad"
        },
        {
          "bundlePath" : "\/Applications\/Xcode-14.0.0-Beta.app\/Contents\/Developer\/Platforms\/iPhoneOS.platform\/Library\/Developer\/CoreSimulator\/Profiles\/DeviceTypes\/iPad Air (3rd generation).simdevicetype",
          "name" : "iPad Air (3rd generation)",
          "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPad-Air--3rd-generation-",
          "productFamily" : "iPad"
        },
        {
          "bundlePath" : "\/Applications\/Xcode-14.0.0-Beta.app\/Contents\/Developer\/Platforms\/iPhoneOS.platform\/Library\/Developer\/CoreSimulator\/Profiles\/DeviceTypes\/iPad (8th generation).simdevicetype",
          "name" : "iPad (8th generation)",
          "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPad--8th-generation-",
          "productFamily" : "iPad"
        },
        {
          "bundlePath" : "\/Applications\/Xcode-14.0.0-Beta.app\/Contents\/Developer\/Platforms\/iPhoneOS.platform\/Library\/Developer\/CoreSimulator\/Profiles\/DeviceTypes\/iPad (9th generation).simdevicetype",
          "name" : "iPad (9th generation)",
          "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPad-9th-generation",
          "productFamily" : "iPad"
        },
        {
          "bundlePath" : "\/Applications\/Xcode-14.0.0-Beta.app\/Contents\/Developer\/Platforms\/iPhoneOS.platform\/Library\/Developer\/CoreSimulator\/Profiles\/DeviceTypes\/iPad Air (4th generation).simdevicetype",
          "name" : "iPad Air (4th generation)",
          "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPad-Air--4th-generation-",
          "productFamily" : "iPad"
        },
        {
          "bundlePath" : "\/Applications\/Xcode-14.0.0-Beta.app\/Contents\/Developer\/Platforms\/iPhoneOS.platform\/Library\/Developer\/CoreSimulator\/Profiles\/DeviceTypes\/iPad Pro (11-inch) (3rd generation).simdevicetype",
          "name" : "iPad Pro (11-inch) (3rd generation)",
          "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPad-Pro-11-inch-3rd-generation",
          "productFamily" : "iPad"
        },
        {
          "bundlePath" : "\/Applications\/Xcode-14.0.0-Beta.app\/Contents\/Developer\/Platforms\/iPhoneOS.platform\/Library\/Developer\/CoreSimulator\/Profiles\/DeviceTypes\/iPad Pro (12.9-inch) (5th generation).simdevicetype",
          "name" : "iPad Pro (12.9-inch) (5th generation)",
          "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPad-Pro-12-9-inch-5th-generation",
          "productFamily" : "iPad"
        },
        {
          "bundlePath" : "\/Applications\/Xcode-14.0.0-Beta.app\/Contents\/Developer\/Platforms\/iPhoneOS.platform\/Library\/Developer\/CoreSimulator\/Profiles\/DeviceTypes\/iPad Air (5th generation).simdevicetype",
          "name" : "iPad Air (5th generation)",
          "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPad-Air-5th-generation",
          "productFamily" : "iPad"
        },
        {
          "bundlePath" : "\/Applications\/Xcode-14.0.0-Beta.app\/Contents\/Developer\/Platforms\/iPhoneOS.platform\/Library\/Developer\/CoreSimulator\/Profiles\/DeviceTypes\/iPad mini (6th generation).simdevicetype",
          "name" : "iPad mini (6th generation)",
          "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPad-mini-6th-generation",
          "productFamily" : "iPad"
        }
      ]
    },
    "dataPath" : "\/Users\/peter.cumming\/Library\/Developer\/CoreSimulator\/Devices\/091E1685-48CC-4D6A-A049-896D552BBF55\/data",
    "lastBootedAt" : "2022-07-29T11:12:40Z",
    "deviceTypeIdentifier" : "com.apple.CoreSimulator.SimDeviceType.iPad-Pro-12-9-inch-5th-generation",
    "udid" : "091E1685-48CC-4D6A-A049-896D552BBF55"
  }
]

12:13:01.093 detox[85896] DEBUG: [EXEC_CMD, #1] applesimutils --list --byId 091E1685-48CC-4D6A-A049-896D552BBF55 --maxResults 1
12:13:01.203 detox[85896] TRACE: [EXEC_SUCCESS, #1] [
  {
    "isAvailable" : true,
    "logPath" : "\/Users\/peter.cumming\/Library\/Logs\/CoreSimulator\/091E1685-48CC-4D6A-A049-896D552BBF55",
    "logPathSize" : 446464,
    "state" : "Booted",
    "name" : "iPad Pro (12.9-inch) (5th generation)",
    "dataPathSize" : 4695351296,
    "deviceType" : {
      "maxRuntimeVersion" : 4294967295,
      "bundlePath" : "\/Applications\/Xcode-14.0.0-Beta.app\/Contents\/Developer\/Platforms\/iPhoneOS.platform\/Library\/Developer\/CoreSimulator\/Profiles\/DeviceTypes\/iPad Pro (12.9-inch) (5th generation).simdevicetype",
      "maxRuntimeVersionString" : "65535.255.255",
      "name" : "iPad Pro (12.9-inch) (5th generation)",
      "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPad-Pro-12-9-inch-5th-generation",
      "productFamily" : "iPad",
      "modelIdentifier" : "iPad13,10",
      "minRuntimeVersionString" : "14.5.0",
      "minRuntimeVersion" : 918784
    },
    "os" : {
      "bundlePath" : "\/Applications\/Xcode-14.0.0-Beta.app\/Contents\/Developer\/Platforms\/iPhoneOS.platform\/Library\/Developer\/CoreSimulator\/Profiles\/Runtimes\/iOS.simruntime",
      "buildversion" : "20A5283p",
      "platform" : "iOS",
      "runtimeRoot" : "\/Applications\/Xcode-14.0.0-Beta.app\/Contents\/Developer\/Platforms\/iPhoneOS.platform\/Library\/Developer\/CoreSimulator\/Profiles\/Runtimes\/iOS.simruntime\/Contents\/Resources\/RuntimeRoot",
      "identifier" : "com.apple.CoreSimulator.SimRuntime.iOS-16-0",
      "version" : "16.0",
      "isInternal" : false,
      "isAvailable" : true,
      "name" : "iOS 16.0",
      "supportedDeviceTypes" : [
        {
          "bundlePath" : "\/Applications\/Xcode-14.0.0-Beta.app\/Contents\/Developer\/Platforms\/iPhoneOS.platform\/Library\/Developer\/CoreSimulator\/Profiles\/DeviceTypes\/iPhone 8.simdevicetype",
          "name" : "iPhone 8",
          "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPhone-8",
          "productFamily" : "iPhone"
        },
        {
          "bundlePath" : "\/Applications\/Xcode-14.0.0-Beta.app\/Contents\/Developer\/Platforms\/iPhoneOS.platform\/Library\/Developer\/CoreSimulator\/Profiles\/DeviceTypes\/iPhone 8 Plus.simdevicetype",
          "name" : "iPhone 8 Plus",
          "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPhone-8-Plus",
          "productFamily" : "iPhone"
        },
        {
          "bundlePath" : "\/Applications\/Xcode-14.0.0-Beta.app\/Contents\/Developer\/Platforms\/iPhoneOS.platform\/Library\/Developer\/CoreSimulator\/Profiles\/DeviceTypes\/iPhone X.simdevicetype",
          "name" : "iPhone X",
          "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPhone-X",
          "productFamily" : "iPhone"
        },
        {
          "bundlePath" : "\/Applications\/Xcode-14.0.0-Beta.app\/Contents\/Developer\/Platforms\/iPhoneOS.platform\/Library\/Developer\/CoreSimulator\/Profiles\/DeviceTypes\/iPhone Xs.simdevicetype",
          "name" : "iPhone Xs",
          "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPhone-XS",
          "productFamily" : "iPhone"
        },
        {
          "bundlePath" : "\/Applications\/Xcode-14.0.0-Beta.app\/Contents\/Developer\/Platforms\/iPhoneOS.platform\/Library\/Developer\/CoreSimulator\/Profiles\/DeviceTypes\/iPhone Xs Max.simdevicetype",
          "name" : "iPhone Xs Max",
          "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPhone-XS-Max",
          "productFamily" : "iPhone"
        },
        {
          "bundlePath" : "\/Applications\/Xcode-14.0.0-Beta.app\/Contents\/Developer\/Platforms\/iPhoneOS.platform\/Library\/Developer\/CoreSimulator\/Profiles\/DeviceTypes\/iPhone Xʀ.simdevicetype",
          "name" : "iPhone Xʀ",
          "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPhone-XR",
          "productFamily" : "iPhone"
        },
        {
          "bundlePath" : "\/Applications\/Xcode-14.0.0-Beta.app\/Contents\/Developer\/Platforms\/iPhoneOS.platform\/Library\/Developer\/CoreSimulator\/Profiles\/DeviceTypes\/iPhone 11.simdevicetype",
          "name" : "iPhone 11",
          "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPhone-11",
          "productFamily" : "iPhone"
        },
        {
          "bundlePath" : "\/Applications\/Xcode-14.0.0-Beta.app\/Contents\/Developer\/Platforms\/iPhoneOS.platform\/Library\/Developer\/CoreSimulator\/Profiles\/DeviceTypes\/iPhone 11 Pro.simdevicetype",
          "name" : "iPhone 11 Pro",
          "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPhone-11-Pro",
          "productFamily" : "iPhone"
        },
        {
          "bundlePath" : "\/Applications\/Xcode-14.0.0-Beta.app\/Contents\/Developer\/Platforms\/iPhoneOS.platform\/Library\/Developer\/CoreSimulator\/Profiles\/DeviceTypes\/iPhone 11 Pro Max.simdevicetype",
          "name" : "iPhone 11 Pro Max",
          "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPhone-11-Pro-Max",
          "productFamily" : "iPhone"
        },
        {
          "bundlePath" : "\/Applications\/Xcode-14.0.0-Beta.app\/Contents\/Developer\/Platforms\/iPhoneOS.platform\/Library\/Developer\/CoreSimulator\/Profiles\/DeviceTypes\/iPhone SE (2nd generation).simdevicetype",
          "name" : "iPhone SE (2nd generation)",
          "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPhone-SE--2nd-generation-",
          "productFamily" : "iPhone"
        },
        {
          "bundlePath" : "\/Applications\/Xcode-14.0.0-Beta.app\/Contents\/Developer\/Platforms\/iPhoneOS.platform\/Library\/Developer\/CoreSimulator\/Profiles\/DeviceTypes\/iPhone 12 mini.simdevicetype",
          "name" : "iPhone 12 mini",
          "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPhone-12-mini",
          "productFamily" : "iPhone"
        },
        {
          "bundlePath" : "\/Applications\/Xcode-14.0.0-Beta.app\/Contents\/Developer\/Platforms\/iPhoneOS.platform\/Library\/Developer\/CoreSimulator\/Profiles\/DeviceTypes\/iPhone 12.simdevicetype",
          "name" : "iPhone 12",
          "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPhone-12",
          "productFamily" : "iPhone"
        },
        {
          "bundlePath" : "\/Applications\/Xcode-14.0.0-Beta.app\/Contents\/Developer\/Platforms\/iPhoneOS.platform\/Library\/Developer\/CoreSimulator\/Profiles\/DeviceTypes\/iPhone 12 Pro.simdevicetype",
          "name" : "iPhone 12 Pro",
          "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPhone-12-Pro",
          "productFamily" : "iPhone"
        },
        {
          "bundlePath" : "\/Applications\/Xcode-14.0.0-Beta.app\/Contents\/Developer\/Platforms\/iPhoneOS.platform\/Library\/Developer\/CoreSimulator\/Profiles\/DeviceTypes\/iPhone 12 Pro Max.simdevicetype",
          "name" : "iPhone 12 Pro Max",
          "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPhone-12-Pro-Max",
          "productFamily" : "iPhone"
        },
        {
          "bundlePath" : "\/Applications\/Xcode-14.0.0-Beta.app\/Contents\/Developer\/Platforms\/iPhoneOS.platform\/Library\/Developer\/CoreSimulator\/Profiles\/DeviceTypes\/iPhone 13 Pro.simdevicetype",
          "name" : "iPhone 13 Pro",
          "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPhone-13-Pro",
          "productFamily" : "iPhone"
        },
        {
          "bundlePath" : "\/Applications\/Xcode-14.0.0-Beta.app\/Contents\/Developer\/Platforms\/iPhoneOS.platform\/Library\/Developer\/CoreSimulator\/Profiles\/DeviceTypes\/iPhone 13 Pro Max.simdevicetype",
          "name" : "iPhone 13 Pro Max",
          "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPhone-13-Pro-Max",
          "productFamily" : "iPhone"
        },
        {
          "bundlePath" : "\/Applications\/Xcode-14.0.0-Beta.app\/Contents\/Developer\/Platforms\/iPhoneOS.platform\/Library\/Developer\/CoreSimulator\/Profiles\/DeviceTypes\/iPhone 13 mini.simdevicetype",
          "name" : "iPhone 13 mini",
          "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPhone-13-mini",
          "productFamily" : "iPhone"
        },
        {
          "bundlePath" : "\/Applications\/Xcode-14.0.0-Beta.app\/Contents\/Developer\/Platforms\/iPhoneOS.platform\/Library\/Developer\/CoreSimulator\/Profiles\/DeviceTypes\/iPhone 13.simdevicetype",
          "name" : "iPhone 13",
          "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPhone-13",
          "productFamily" : "iPhone"
        },
        {
          "bundlePath" : "\/Applications\/Xcode-14.0.0-Beta.app\/Contents\/Developer\/Platforms\/iPhoneOS.platform\/Library\/Developer\/CoreSimulator\/Profiles\/DeviceTypes\/iPhone SE (3rd generation).simdevicetype",
          "name" : "iPhone SE (3rd generation)",
          "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPhone-SE-3rd-generation",
          "productFamily" : "iPhone"
        },
        {
          "bundlePath" : "\/Applications\/Xcode-14.0.0-Beta.app\/Contents\/Developer\/Platforms\/iPhoneOS.platform\/Library\/Developer\/CoreSimulator\/Profiles\/DeviceTypes\/iPad Pro (9.7-inch).simdevicetype",
          "name" : "iPad Pro (9.7-inch)",
          "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPad-Pro--9-7-inch-",
          "productFamily" : "iPad"
        },
        {
          "bundlePath" : "\/Applications\/Xcode-14.0.0-Beta.app\/Contents\/Developer\/Platforms\/iPhoneOS.platform\/Library\/Developer\/CoreSimulator\/Profiles\/DeviceTypes\/iPad Pro (12.9-inch) (1st generation).simdevicetype",
          "name" : "iPad Pro (12.9-inch) (1st generation)",
          "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPad-Pro",
          "productFamily" : "iPad"
        },
        {
          "bundlePath" : "\/Applications\/Xcode-14.0.0-Beta.app\/Contents\/Developer\/Platforms\/iPhoneOS.platform\/Library\/Developer\/CoreSimulator\/Profiles\/DeviceTypes\/iPad (5th generation).simdevicetype",
          "name" : "iPad (5th generation)",
          "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPad--5th-generation-",
          "productFamily" : "iPad"
        },
        {
          "bundlePath" : "\/Applications\/Xcode-14.0.0-Beta.app\/Contents\/Developer\/Platforms\/iPhoneOS.platform\/Library\/Developer\/CoreSimulator\/Profiles\/DeviceTypes\/iPad Pro (12.9-inch) (2nd generation).simdevicetype",
          "name" : "iPad Pro (12.9-inch) (2nd generation)",
          "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPad-Pro--12-9-inch---2nd-generation-",
          "productFamily" : "iPad"
        },
        {
          "bundlePath" : "\/Applications\/Xcode-14.0.0-Beta.app\/Contents\/Developer\/Platforms\/iPhoneOS.platform\/Library\/Developer\/CoreSimulator\/Profiles\/DeviceTypes\/iPad Pro (10.5-inch).simdevicetype",
          "name" : "iPad Pro (10.5-inch)",
          "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPad-Pro--10-5-inch-",
          "productFamily" : "iPad"
        },
        {
          "bundlePath" : "\/Applications\/Xcode-14.0.0-Beta.app\/Contents\/Developer\/Platforms\/iPhoneOS.platform\/Library\/Developer\/CoreSimulator\/Profiles\/DeviceTypes\/iPad (6th generation).simdevicetype",
          "name" : "iPad (6th generation)",
          "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPad--6th-generation-",
          "productFamily" : "iPad"
        },
        {
          "bundlePath" : "\/Applications\/Xcode-14.0.0-Beta.app\/Contents\/Developer\/Platforms\/iPhoneOS.platform\/Library\/Developer\/CoreSimulator\/Profiles\/DeviceTypes\/iPad (7th generation).simdevicetype",
          "name" : "iPad (7th generation)",
          "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPad--7th-generation-",
          "productFamily" : "iPad"
        },
        {
          "bundlePath" : "\/Applications\/Xcode-14.0.0-Beta.app\/Contents\/Developer\/Platforms\/iPhoneOS.platform\/Library\/Developer\/CoreSimulator\/Profiles\/DeviceTypes\/iPad Pro (11-inch) (1st generation).simdevicetype",
          "name" : "iPad Pro (11-inch) (1st generation)",
          "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPad-Pro--11-inch-",
          "productFamily" : "iPad"
        },
        {
          "bundlePath" : "\/Applications\/Xcode-14.0.0-Beta.app\/Contents\/Developer\/Platforms\/iPhoneOS.platform\/Library\/Developer\/CoreSimulator\/Profiles\/DeviceTypes\/iPad Pro (12.9-inch) (3rd generation).simdevicetype",
          "name" : "iPad Pro (12.9-inch) (3rd generation)",
          "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPad-Pro--12-9-inch---3rd-generation-",
          "productFamily" : "iPad"
        },
        {
          "bundlePath" : "\/Applications\/Xcode-14.0.0-Beta.app\/Contents\/Developer\/Platforms\/iPhoneOS.platform\/Library\/Developer\/CoreSimulator\/Profiles\/DeviceTypes\/iPad Pro (11-inch) (2nd generation).simdevicetype",
          "name" : "iPad Pro (11-inch) (2nd generation)",
          "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPad-Pro--11-inch---2nd-generation-",
          "productFamily" : "iPad"
        },
        {
          "bundlePath" : "\/Applications\/Xcode-14.0.0-Beta.app\/Contents\/Developer\/Platforms\/iPhoneOS.platform\/Library\/Developer\/CoreSimulator\/Profiles\/DeviceTypes\/iPad Pro (12.9-inch) (4th generation).simdevicetype",
          "name" : "iPad Pro (12.9-inch) (4th generation)",
          "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPad-Pro--12-9-inch---4th-generation-",
          "productFamily" : "iPad"
        },
        {
          "bundlePath" : "\/Applications\/Xcode-14.0.0-Beta.app\/Contents\/Developer\/Platforms\/iPhoneOS.platform\/Library\/Developer\/CoreSimulator\/Profiles\/DeviceTypes\/iPad mini (5th generation).simdevicetype",
          "name" : "iPad mini (5th generation)",
          "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPad-mini--5th-generation-",
          "productFamily" : "iPad"
        },
        {
          "bundlePath" : "\/Applications\/Xcode-14.0.0-Beta.app\/Contents\/Developer\/Platforms\/iPhoneOS.platform\/Library\/Developer\/CoreSimulator\/Profiles\/DeviceTypes\/iPad Air (3rd generation).simdevicetype",
          "name" : "iPad Air (3rd generation)",
          "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPad-Air--3rd-generation-",
          "productFamily" : "iPad"
        },
        {
          "bundlePath" : "\/Applications\/Xcode-14.0.0-Beta.app\/Contents\/Developer\/Platforms\/iPhoneOS.platform\/Library\/Developer\/CoreSimulator\/Profiles\/DeviceTypes\/iPad (8th generation).simdevicetype",
          "name" : "iPad (8th generation)",
          "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPad--8th-generation-",
          "productFamily" : "iPad"
        },
        {
          "bundlePath" : "\/Applications\/Xcode-14.0.0-Beta.app\/Contents\/Developer\/Platforms\/iPhoneOS.platform\/Library\/Developer\/CoreSimulator\/Profiles\/DeviceTypes\/iPad (9th generation).simdevicetype",
          "name" : "iPad (9th generation)",
          "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPad-9th-generation",
          "productFamily" : "iPad"
        },
        {
          "bundlePath" : "\/Applications\/Xcode-14.0.0-Beta.app\/Contents\/Developer\/Platforms\/iPhoneOS.platform\/Library\/Developer\/CoreSimulator\/Profiles\/DeviceTypes\/iPad Air (4th generation).simdevicetype",
          "name" : "iPad Air (4th generation)",
          "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPad-Air--4th-generation-",
          "productFamily" : "iPad"
        },
        {
          "bundlePath" : "\/Applications\/Xcode-14.0.0-Beta.app\/Contents\/Developer\/Platforms\/iPhoneOS.platform\/Library\/Developer\/CoreSimulator\/Profiles\/DeviceTypes\/iPad Pro (11-inch) (3rd generation).simdevicetype",
          "name" : "iPad Pro (11-inch) (3rd generation)",
          "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPad-Pro-11-inch-3rd-generation",
          "productFamily" : "iPad"
        },
        {
          "bundlePath" : "\/Applications\/Xcode-14.0.0-Beta.app\/Contents\/Developer\/Platforms\/iPhoneOS.platform\/Library\/Developer\/CoreSimulator\/Profiles\/DeviceTypes\/iPad Pro (12.9-inch) (5th generation).simdevicetype",
          "name" : "iPad Pro (12.9-inch) (5th generation)",
          "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPad-Pro-12-9-inch-5th-generation",
          "productFamily" : "iPad"
        },
        {
          "bundlePath" : "\/Applications\/Xcode-14.0.0-Beta.app\/Contents\/Developer\/Platforms\/iPhoneOS.platform\/Library\/Developer\/CoreSimulator\/Profiles\/DeviceTypes\/iPad Air (5th generation).simdevicetype",
          "name" : "iPad Air (5th generation)",
          "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPad-Air-5th-generation",
          "productFamily" : "iPad"
        },
        {
          "bundlePath" : "\/Applications\/Xcode-14.0.0-Beta.app\/Contents\/Developer\/Platforms\/iPhoneOS.platform\/Library\/Developer\/CoreSimulator\/Profiles\/DeviceTypes\/iPad mini (6th generation).simdevicetype",
          "name" : "iPad mini (6th generation)",
          "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPad-mini-6th-generation",
          "productFamily" : "iPad"
        }
      ]
    },
    "dataPath" : "\/Users\/peter.cumming\/Library\/Developer\/CoreSimulator\/Devices\/091E1685-48CC-4D6A-A049-896D552BBF55\/data",
    "lastBootedAt" : "2022-07-29T11:12:40Z",
    "deviceTypeIdentifier" : "com.apple.CoreSimulator.SimDeviceType.iPad-Pro-12-9-inch-5th-generation",
    "udid" : "091E1685-48CC-4D6A-A049-896D552BBF55"
  }
]

12:13:01.205 detox[85896] TRACE: [ARTIFACTS_LIFECYCLE] artifactsManager.onBootDevice({
  deviceId: '091E1685-48CC-4D6A-A049-896D552BBF55',
  type: 'ios.simulator',
  coldBoot: false
})
12:13:01.219 detox[85896] TRACE: [ARTIFACTS_LIFECYCLE] artifactsManager.onBeforeTerminateApp({
  deviceId: '091E1685-48CC-4D6A-A049-896D552BBF55',
  bundleId: 'com.COMPANY.PRODUCT'
})
12:13:01.219 detox[85896] DEBUG: [EXEC_CMD, #2] /usr/bin/xcrun simctl terminate 091E1685-48CC-4D6A-A049-896D552BBF55 com.COMPANY.PRODUCT
12:13:01.220 detox[85896] DEBUG: [EXEC_TRY, #2] Terminating com.COMPANY.PRODUCT...
12:13:01.337 detox[85896] DEBUG: [EXEC_SUCCESS, #2] com.COMPANY.PRODUCT terminated
12:13:01.338 detox[85896] TRACE: [ARTIFACTS_LIFECYCLE] artifactsManager.onTerminateApp({
  deviceId: '091E1685-48CC-4D6A-A049-896D552BBF55',
  bundleId: 'com.COMPANY.PRODUCT'
})
12:13:01.338 detox[85896] TRACE: [ARTIFACTS_LIFECYCLE] artifactsManager.onBeforeUninstallApp({
  deviceId: '091E1685-48CC-4D6A-A049-896D552BBF55',
  bundleId: 'com.COMPANY.PRODUCT'
})
12:13:01.338 detox[85896] DEBUG: [EXEC_CMD, #3] /usr/bin/xcrun simctl uninstall 091E1685-48CC-4D6A-A049-896D552BBF55 com.COMPANY.PRODUCT
12:13:01.338 detox[85896] DEBUG: [EXEC_TRY, #3] Uninstalling com.COMPANY.PRODUCT...
12:13:01.914 detox[85896] DEBUG: [EXEC_SUCCESS, #3] com.COMPANY.PRODUCT uninstalled
12:13:01.915 detox[85896] TRACE: [ARTIFACTS_LIFECYCLE] artifactsManager.onBeforeTerminateApp({
  deviceId: '091E1685-48CC-4D6A-A049-896D552BBF55',
  bundleId: 'com.COMPANY.PRODUCT'
})
12:13:01.915 detox[85896] DEBUG: [EXEC_CMD, #4] /usr/bin/xcrun simctl terminate 091E1685-48CC-4D6A-A049-896D552BBF55 com.COMPANY.PRODUCT
12:13:01.915 detox[85896] DEBUG: [EXEC_TRY, #4] Terminating com.COMPANY.PRODUCT...
12:13:03.066 detox[85896] TRACE: [EXEC_TRY_FAIL, #4] An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=3):
The operation couldn’t be completed. found nothing to terminate
found nothing to terminate

12:13:03.067 detox[85896] DEBUG: [EXEC_TRY, #4] Terminating com.COMPANY.PRODUCT...
12:13:03.224 detox[85896] DEBUG: [EXEC_FAIL, #4] "/usr/bin/xcrun simctl terminate 091E1685-48CC-4D6A-A049-896D552BBF55 com.COMPANY.PRODUCT" failed with error = ChildProcessError: Command failed: /usr/bin/xcrun simctl terminate 091E1685-48CC-4D6A-A049-896D552BBF55 com.COMPANY.PRODUCT
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=3):
The operation couldn’t be completed. found nothing to terminate
found nothing to terminate
 `/usr/bin/xcrun simctl terminate 091E1685-48CC-4D6A-A049-896D552BBF55 com.COMPANY.PRODUCT` (exited with error code 3) (code=3), stdout and stderr:

12:13:03.224 detox[85896] DEBUG: [EXEC_FAIL, #4] 
12:13:03.224 detox[85896] DEBUG: [EXEC_FAIL, #4] An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=3):
The operation couldn’t be completed. found nothing to terminate
found nothing to terminate

12:13:03.225 detox[85896] ERROR: Command failed: /usr/bin/xcrun simctl terminate 091E1685-48CC-4D6A-A049-896D552BBF55 com.COMPANY.PRODUCT
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=3):
The operation couldn’t be completed. found nothing to terminate
found nothing to terminate
 `/usr/bin/xcrun simctl terminate 091E1685-48CC-4D6A-A049-896D552BBF55 com.COMPANY.PRODUCT` (exited with error code 3)
12:13:04.171 detox[85896] INFO:  admin modal is assigned to undefined
12:13:04.171 detox[85896] INFO:  admin modal: admin modal displayed
12:13:04.172 detox[85896] INFO:  admin modal: admin modal displayed [FAIL]
12:13:04.172 detox[85896] INFO:  admin modal: admin modal not displayed
12:13:04.172 detox[85896] INFO:  admin modal: admin modal not displayed [FAIL]

12:13:04.183 detox[85896] TRACE: [ARTIFACTS_LIFECYCLE] artifactsManager.onBeforeCleanup()
12:13:04.187 detox[85896] DEBUG: [EXEC_CMD, #5] /usr/bin/xcrun simctl shutdown 091E1685-48CC-4D6A-A049-896D552BBF55
12:13:04.187 detox[85896] DEBUG: [EXEC_TRY, #5] Shutting down 091E1685-48CC-4D6A-A049-896D552BBF55...
12:13:04.194 detox[85896] TRACE: [SESSION_TORN] tester exited session f8e7e827-c480-fa70-2b4e-8cf44f869d2c
12:13:07.379 detox[85896] DEBUG: [EXEC_SUCCESS, #5] 091E1685-48CC-4D6A-A049-896D552BBF55 shut down
12:13:07.380 detox[85896] DEBUG: [WSS_CLOSE] Detox server has been closed gracefully
 FAIL  e2e/tests/adminModal.e2e.ts (7.082s)
  ● admin modal › admin modal displayed

    Environment setup failed. See the detailed error below.



  ● admin modal › admin modal not displayed

    Environment setup failed. See the detailed error below.




  ● Test suite failed to run

    ChildProcessError: Command failed: /usr/bin/xcrun simctl terminate 091E1685-48CC-4D6A-A049-896D552BBF55 com.COMPANY.PRODUCT
    An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=3):
    The operation couldn’t be completed. found nothing to terminate
    found nothing to terminate
     `/usr/bin/xcrun simctl terminate 091E1685-48CC-4D6A-A049-896D552BBF55 com.COMPANY.PRODUCT` (exited with error code 3)

      at callback (../node_modules/child-process-promise/lib/index.js:33:27)


Summary of tests

tests/adminModal.e2e.ts
  admin modal
    ✕ admin modal displayed
    ✕ admin modal not displayed

12:13:07.506 detox[85895] ERROR: [cli.js] Command failed: jest --config e2e/config.json --testNamePattern '^((?!:android:).)*$' --maxWorkers 1 adminModal.e2e.ts
```

</details>

### Device logs

<details><summary>Device logs</summary>

```
peter.cumming@HUD040089 ios % yarn e2e-run adminModal.e2e.ts --record-logs all
➤ YN0000: executing [e2e-run]: detox test -l verbose --record-logs failing --take-screenshots failing --record-videos failing --configuration ios
12:15:26.937 detox[86015] INFO:  [test.js] DETOX_CONFIGURATION="ios" DETOX_LOGLEVEL="verbose" DETOX_RECORD_LOGS="all" DETOX_RECORD_VIDEOS="failing" DETOX_REPORT_SPECS=true DETOX_START_TIMESTAMP=1659093326931 DETOX_TAKE_SCREENSHOTS="failing" DETOX_USE_CUSTOM_LOGGER=true jest --config e2e/config.json --testNamePattern '^((?!:android:).)*$' --maxWorkers 1 adminModal.e2e.ts
watchman warning:  Recrawled this watch 145 times, most recently because:
MustScanSubDirs UserDroppedTo resolve, please review the information on
https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl
To clear this warning, run:
`watchman watch-del '/Users/peter.cumming/COMPANY_Repos/PRODUCT-mobile' ; watchman watch-project '/Users/peter.cumming/COMPANY_Repos/PRODUCT-mobile'`

12:15:27.629 detox[86016] DEBUG: [WSS_CREATE] Detox server listening on localhost:64041...
12:15:27.635 detox[86016] DEBUG: [WSS_CONNECTION, #64042] registered a new connection.
12:15:27.797 detox[86016] DEBUG: [EXEC_CMD, #0] applesimutils --list --byType "iPad Pro (12.9-inch) (5th generation)"
12:15:27.936 detox[86016] DEBUG: [EXEC_CMD, #1] applesimutils --list --byId 091E1685-48CC-4D6A-A049-896D552BBF55 --maxResults 1
12:15:28.032 detox[86016] DEBUG: [EXEC_CMD, #2] /usr/bin/xcrun simctl boot 091E1685-48CC-4D6A-A049-896D552BBF55 
12:15:28.032 detox[86016] DEBUG: [EXEC_TRY, #2] Booting device 091E1685-48CC-4D6A-A049-896D552BBF55...
12:15:28.517 detox[86016] DEBUG: [EXEC_CMD, #3] /usr/bin/xcrun simctl bootstatus 091E1685-48CC-4D6A-A049-896D552BBF55
12:15:32.646 detox[86016] DEBUG: [EXEC_CMD, #4] /usr/bin/xcrun simctl io 091E1685-48CC-4D6A-A049-896D552BBF55 screenshot "/dev/null"
12:15:33.335 detox[86016] DEBUG: [EXEC_CMD, #5] /usr/bin/xcrun simctl terminate 091E1685-48CC-4D6A-A049-896D552BBF55 com.COMPANY.PRODUCT
12:15:33.335 detox[86016] DEBUG: [EXEC_TRY, #5] Terminating com.COMPANY.PRODUCT...
12:15:34.448 detox[86016] DEBUG: [EXEC_TRY, #5] Terminating com.COMPANY.PRODUCT...
12:15:34.609 detox[86016] DEBUG: [EXEC_FAIL, #5] "/usr/bin/xcrun simctl terminate 091E1685-48CC-4D6A-A049-896D552BBF55 com.COMPANY.PRODUCT" failed with error = ChildProcessError: Command failed: /usr/bin/xcrun simctl terminate 091E1685-48CC-4D6A-A049-896D552BBF55 com.COMPANY.PRODUCT
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=3):
The operation couldn’t be completed. found nothing to terminate
found nothing to terminate
 `/usr/bin/xcrun simctl terminate 091E1685-48CC-4D6A-A049-896D552BBF55 com.COMPANY.PRODUCT` (exited with error code 3) (code=3), stdout and stderr:

12:15:34.610 detox[86016] DEBUG: [EXEC_FAIL, #5] 
12:15:34.610 detox[86016] DEBUG: [EXEC_FAIL, #5] An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=3):
The operation couldn’t be completed. found nothing to terminate
found nothing to terminate

12:15:34.610 detox[86016] ERROR: Command failed: /usr/bin/xcrun simctl terminate 091E1685-48CC-4D6A-A049-896D552BBF55 com.COMPANY.PRODUCT
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=3):
The operation couldn’t be completed. found nothing to terminate
found nothing to terminate
 `/usr/bin/xcrun simctl terminate 091E1685-48CC-4D6A-A049-896D552BBF55 com.COMPANY.PRODUCT` (exited with error code 3)
12:15:36.609 detox[86016] INFO:  admin modal is assigned to undefined
12:15:36.609 detox[86016] INFO:  admin modal: admin modal displayed
12:15:36.609 detox[86016] INFO:  admin modal: admin modal displayed [FAIL]
12:15:36.610 detox[86016] INFO:  admin modal: admin modal not displayed
12:15:36.610 detox[86016] INFO:  admin modal: admin modal not displayed [FAIL]

12:15:36.622 detox[86016] DEBUG: [MOVE_FILE] moving "/private/var/folders/n4/hcp3g49n21g75w5pk8_trwvwmk1krd/T/a91200a6-647e-4135-a410-656b1d9e0f2f.detox.log" to artifacts/ios.2022-07-29 11-15-26Z/detox_pid_86016.json.log
12:15:36.623 detox[86016] DEBUG: [MOVE_FILE] moving "/private/var/folders/n4/hcp3g49n21g75w5pk8_trwvwmk1krd/T/55543ae0-a2df-4871-8c2e-1601a6ee44fe.detox.log" to artifacts/ios.2022-07-29 11-15-26Z/detox_pid_86016.log
12:15:36.626 detox[86016] DEBUG: [EXEC_CMD, #6] /usr/bin/xcrun simctl shutdown 091E1685-48CC-4D6A-A049-896D552BBF55
12:15:36.626 detox[86016] DEBUG: [EXEC_TRY, #6] Shutting down 091E1685-48CC-4D6A-A049-896D552BBF55...
12:15:39.792 detox[86016] DEBUG: [EXEC_SUCCESS, #6] 091E1685-48CC-4D6A-A049-896D552BBF55 shut down
12:15:39.793 detox[86016] DEBUG: [WSS_CLOSE] Detox server has been closed gracefully
 FAIL  e2e/tests/adminModal.e2e.ts (12.35s)
  ● admin modal › admin modal displayed

    Environment setup failed. See the detailed error below.



  ● admin modal › admin modal not displayed

    Environment setup failed. See the detailed error below.




  ● Test suite failed to run

    ChildProcessError: Command failed: /usr/bin/xcrun simctl terminate 091E1685-48CC-4D6A-A049-896D552BBF55 com.COMPANY.PRODUCT
    An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=3):
    The operation couldn’t be completed. found nothing to terminate
    found nothing to terminate
     `/usr/bin/xcrun simctl terminate 091E1685-48CC-4D6A-A049-896D552BBF55 com.COMPANY.PRODUCT` (exited with error code 3)

      at callback (../node_modules/child-process-promise/lib/index.js:33:27)


Summary of tests

tests/adminModal.e2e.ts
  admin modal
    ✕ admin modal displayed
    ✕ admin modal not displayed

12:15:39.920 detox[86015] ERROR: [cli.js] Command failed: jest --config e2e/config.json --testNamePattern '^((?!:android:).)*$' --maxWorkers 1 adminModal.e2e.ts
```

</details>

**Comment by asafkorem** [comment]
@Peter-Cumming - thanks to @mikehardy, this issue was resolved in https://github.com/wix/Detox/pull/3551. We'll release a patch version later today 🙂

**Comment by asafkorem** [comment]
Version [19.9.2](https://github.com/wix/Detox/releases/tag/19.9.2) was released with @mikehardy's fix.

**Comment by jaredkotoff** [comment]
I'm still seeing this issue on 19.10.0 even though it looks like the error should match the changes to 19.9.2
xcodebuild -version: `Xcode 14.0 Build version 14A5270f`

Any tips or ideas here?

```

detox[43229] ERROR: [DETOX_INIT_ERROR]
 ChildProcessError: Command failed: /usr/bin/xcrun simctl terminate F578BBF9-50F9-4799-B6A7-9AF1C449E120 com.appname
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=3):
The operation couldn’t be completed. found nothing to terminate
found nothing to terminate
 `/usr/bin/xcrun simctl terminate F578BBF9-50F9-4799-B6A7-9AF1C449E120 com.appname` (exited with error code 3)
    at callback (/appname/client/www/native_v2/build/node_modules/child-process-promise/lib/index.js:33:27)
    at ChildProcess.exithandler (node:child_process:406:5)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5) {
  code: 3,
  childProcess: {
    _forkChild: [Function: _forkChild],
    ChildProcess: [Function: ChildProcess],
    exec: [Function: exec],
    execFile: [Function: execFile],
    execFileSync: [Function: execFileSync],
    execSync: [Function: execSync],
    fork: [Function: fork],
    spawn: [Function: spawn],
    spawnSync: [Function: spawnSync]
  },
  stdout: '',
  stderr: 'An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=3):\n' +
    'The operation couldn’t be completed. found nothing to terminate\n' +
    'found nothing to terminate\n'
}
  1) "before all" hook in "{root}"

  0 passing (2s)
  1 failing

  1) "before all" hook in "{root}":
     ChildProcessError: Command failed: /usr/bin/xcrun simctl terminate F578BBF9-50F9-4799-B6A7-9AF1C449E120 com.appname
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=3):
The operation couldn’t be completed. found nothing to terminate
found nothing to terminate
 `/usr/bin/xcrun simctl terminate F578BBF9-50F9-4799-B6A7-9AF1C449E120 com.appname` (exited with error code 3)
      at callback (build/node_modules/child-process-promise/lib/index.js:33:27)
      at ChildProcess.exithandler (node:child_process:406:5)
      at ChildProcess.emit (node:events:527:28)
      at maybeClose (node:internal/child_process:1092:16)
      at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)


detox[43227] ERROR: [cli.js] Command failed: mocha --opts tests/mocha.opts --configuration ios.sim.debug --grep :android: --invert --artifacts-location ./build/testSummary/ --record-logs all --use-custom-logger true build
```

**Comment by asafkorem** [comment]
@jaredkotoff please make sure you have the correct Detox version in your node-modules (`npm ls detox`)
