### ISSUE TITLE
allow absolute app path

### ISSUE THREAD

**Issue by chirag04** [wix/detox#98]
Right now the detox config in package.json expect the app path to be relative to the current project dir. This is not always true especially in CI environments. Locally, xcode default to `/Library/....` which can be overridden but it would be nice to support absolute paths.

```json
"ios-simulator.debug": {
    "app": "~/Users/chirag/Library/Developer/Xcode/DerivedData/comlink-gnjeyymjpticnpbxoszwvizawxui/Build/Products/Debug-iphonesimulator/comlink.app",
    "device": "iPhone 6s"
},
```

**Comment by LeoNatan** [comment]
I am not familiar with such requirement. Have you tried it and seen an issue?

**Comment by rotemmiz** [comment]
Hi @chirag04, 

Although not technically hard to implement this feature, I am not in favor of adding absolute paths in configuration (of any kind) for the following reasons:

1. Absolute paths will not work across machines (by definition). If your CI machine has a different user than your development machine, you would have to fiddle with the configuration between these machines.
2. CI machines should build their artifacts in a specific work dir, not in a global directory. Imagine what happens when you run two concurrent builds on the same machine, will one build delete the artifacts of the other ? 
3. There's an easy way of telling `xcodebuild` to change the derivedData path, by adding `--derivedDataPath relative/path/here`.
4. If you use react-native, that's exactly what `react-native run-ios` does, and that's a very good practice.

**Comment by chirag04** [comment]
@rotemmiz 

> CI machines should build their artifacts in a specific work dir, not in a global directory. Imagine what happens when you run two concurrent builds on the same machine, will one build delete the artifacts of the other.

CI builds run in containers so they don't override each others artifacts. what i'm saying is that the artifact directory may not always be inside the project work directory. eg:

build 1: artifact directory: `/etc/asdeasda-some-container-id/artifacts/app.ipa` while the project is at `/etc/asdeasda-some-container-id/source/xcodeproject-here`

build 2: will essentially have the same path just that he container-id changes above.

Anyway, i think the bigger point here is that it's not always necessary that ipa path will be inside the project directory. it would be nice to support that.

**Comment by LeoNatan** [comment]
@rotemmiz I think this has been resolved. Right?

**Comment by rotemmiz** [comment]
No, we don't support absolute paths. I'm still not convinced it's needed, but PRs for a non breaking support are welcome

**Comment by LeoNatan** [comment]
What happens if I provide an absolute path in `binaryPath`?

**Comment by seantimm** [comment]
My CI environment on Bitrise is dumping my archive in an absolute path outside of my project folder.   I'll work around it by adding a copy step for now.

**Comment by chirag04** [comment]
bitrise is exactly the reason why i opened this issue.

**Comment by rotemmiz** [comment]
Hey guys,

If this is something you want to take forward a PR would be appreciated. We are unable to put time into this currently.

**Comment by silyevsk** [comment]
Done
